'use client';

import { useState } from 'react';
import { addDoc, collection, serverTimestamp } from 'firebase/firestore';
import { auth, db } from '../lib/firebase';
import { Rocket, Film, Sparkles } from 'lucide-react';

export default function NaxStudio() {
  const [botName,setBotName]=useState(''); const [trigger,setTrigger]=useState(''); const [reply,setReply]=useState(''); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false);
  const publish=async()=>{if(!botName.trim()||!trigger.trim()||!reply.trim()||!auth.currentUser)return;setBusy(true);try{await addDoc(collection(db,'custom_bots'),{botName:botName.trim(),creatorId:auth.currentUser.uid,creatorName:auth.currentUser.displayName||'Unknown',rules:[{trigger:trigger.trim().toLowerCase(),reply:reply.trim()}],type:'custom',installs:0,createdAt:serverTimestamp()});setBotName('');setTrigger('');setReply('');setDone(true)}finally{setBusy(false)}};
  return <div className="glass rounded-3xl p-5"><div className="flex items-center gap-3"><div className="rounded-2xl bg-indigo-500/15 p-3"><Sparkles/></div><div><h2 className="font-bold">Nax Studio</h2><p className="text-sm text-slate-500">Build and deploy custom bots.</p></div></div><div className="mt-5 rounded-2xl bg-white/5 p-4"><div className="mb-4 flex items-center gap-2 font-semibold"><Film className="h-4 w-4"/> Templates</div><div className="rounded-xl bg-white/5 p-3"><div className="font-medium">MovieBot Template</div><div className="text-xs text-slate-500">Search/link logic template</div></div></div><div className="mt-4 space-y-3"><input value={botName} onChange={e=>setBotName(e.target.value)} placeholder="Bot name" className="w-full rounded-2xl bg-white/10 px-4 py-3 outline-none"/><div className="rounded-2xl border border-indigo-400/30 bg-indigo-500/5 p-4"><p className="mb-3 text-sm font-bold text-indigo-400">BOT LOGIC / RULES</p><input value={trigger} onChange={e=>setTrigger(e.target.value)} placeholder="If user says… e.g. hello" className="mb-3 w-full rounded-xl bg-white/10 px-4 py-3 outline-none"/><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Bot replies with…" rows={3} className="w-full rounded-xl bg-white/10 px-4 py-3 outline-none"/></div><button disabled={busy} onClick={publish} className="flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-indigo-500 to-cyan-500 py-3 font-bold"><Rocket className="h-4 w-4"/>{busy?'Deploying…':'Deploy Bot to Ecosystem 🚀'}</button>{done&&<p className="text-center text-sm text-emerald-400">Bot deployed successfully.</p>}</div></div>;
}
