'use client';

import React, { useEffect, useState } from 'react';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut, User } from 'firebase/auth';
import { Bot, Download, FileUp, Globe2, LogOut, MessageCircle, Plus, Search, Send, Settings, Sparkles, UserRound, Wifi, X, Zap } from 'lucide-react';
import { auth } from '../lib/firebase';
import { createPrivateChat, searchNaxUser, sendTextMessage, subscribeToMessages, subscribeToPrivateChats, ChatMessage, NaxUser } from '../lib/naxChat';
import { useWebRTC } from '../hooks/useWebRTC';
import TransferZone from '../components/TransferZone';

const formatBytes = (bytes: number) => {
  if (!bytes) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.min(Math.floor(Math.log(bytes) / Math.log(1024)), units.length - 1);
  return `${(bytes / Math.pow(1024, i)).toFixed(i ? 1 : 0)} ${units[i]}`;
};

export default function HyperDropHome() {
  const [user, setUser] = useState<User | null>(null);
  const [authLoading, setAuthLoading] = useState(true);
  useEffect(() => onAuthStateChanged(auth, (value) => { setUser(value); setAuthLoading(false); }), []);

  if (authLoading) return <div className="flex min-h-screen items-center justify-center bg-slate-950 text-slate-400">Loading HyperDrop…</div>;
  if (!user) return <AuthPanel />;
  return <AppShell user={user} />;
}

function AuthPanel() {
  const [mode, setMode] = useState<'login' | 'signup'>('login');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setError('');
    try { if (mode === 'login') await signInWithEmailAndPassword(auth, email, password); else await createUserWithEmailAndPassword(auth, email, password); }
    catch (e: any) { setError(e?.message?.replace('Firebase: ', '') || 'Authentication failed.'); }
  };
  return <div className="flex min-h-screen items-center justify-center bg-slate-950 px-5 text-white"><div className="glass w-full max-w-md rounded-[32px] p-8"><div className="mb-8 text-center"><div className="mx-auto mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-indigo-500 to-cyan-400 shadow-lg shadow-cyan-500/20"><Zap className="h-8 w-8" /></div><h1 className="text-3xl font-black">HyperDrop</h1><p className="mt-2 text-sm text-slate-400">Nax Chat + private P2P in one app</p></div><form onSubmit={submit} className="space-y-3"><input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="Email" className="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3.5 outline-none focus:border-cyan-400/50" /><input required minLength={6} type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Password" className="w-full rounded-2xl border border-white/10 bg-black/20 px-4 py-3.5 outline-none focus:border-cyan-400/50" />{error && <p className="rounded-xl bg-red-400/10 p-3 text-xs text-red-200">{error}</p>}<button className="w-full rounded-2xl bg-gradient-to-r from-indigo-500 to-cyan-500 py-3.5 font-bold">{mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button type="button" onClick={() => setMode(mode === 'login' ? 'signup' : 'login')} className="mt-5 w-full text-sm text-slate-400 hover:text-white">{mode === 'login' ? 'New here? Create an account' : 'Already have an account? Sign in'}</button></div></div>;
}

function AppShell({ user }: { user: User }) {
  const [tab, setTab] = useState<'chats' | 'drop' | 'moments' | 'explore' | 'profile'>('chats');
  const [chats, setChats] = useState<any[]>([]);
  const [selected, setSelected] = useState<any | null>(null);
  useEffect(() => subscribeToPrivateChats(user.uid, setChats), [user.uid]);
  return <div className="min-h-screen text-slate-100"><header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/70 backdrop-blur-2xl"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><div className="flex items-center gap-3"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 to-cyan-400"><Zap className="h-5 w-5" /></div><div className="font-black tracking-tight">HyperDrop</div></div><div className="flex items-center gap-2"><span className="hidden text-xs text-slate-500 sm:block">{user.email}</span><button onClick={() => signOut(auth)} className="rounded-xl p-2 text-slate-400 hover:bg-white/5 hover:text-white" aria-label="Sign out"><LogOut className="h-4 w-4" /></button></div></div></header><main className="mx-auto max-w-6xl px-4 pb-28 pt-6">{tab === 'chats' && <ChatsHome chats={chats} selected={selected} setSelected={setSelected} />}{tab === 'drop' && <DropHome />}{tab === 'moments' && <FeaturePlaceholder title="Moments" icon={<Sparkles />} text="Nax Chat Moments will live here — media-first posts and updates." />}{tab === 'explore' && <FeaturePlaceholder title="Explore" icon={<Globe2 />} text="Portals, bots, mini apps and Nax Studio are being ported into the web app." />}{tab === 'profile' && <FeaturePlaceholder title="Profile & Settings" icon={<UserRound />} text={user.email || 'Your HyperDrop profile'} />}</main><nav className="fixed bottom-4 left-1/2 z-50 flex w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 items-center justify-around rounded-2xl border border-white/10 bg-slate-900/85 p-2 shadow-2xl backdrop-blur-2xl">{[["chats",<MessageCircle/>,'Chats'],['drop',<FileUp/>,'Drop'],['moments',<Sparkles/>,'Moments'],['explore',<Globe2/>,'Explore'],['profile',<UserRound/>,'Profile']].map(([id, icon, label]) => <button key={id as string} onClick={() => setTab(id as any)} className={`flex flex-1 flex-col items-center gap-1 rounded-xl py-2 text-[10px] ${tab === id ? 'bg-white/10 text-cyan-300' : 'text-slate-500'}`}>{React.cloneElement(icon as React.ReactElement, { className: 'h-5 w-5' })}{label}</button>)}</nav></div>;
}

function ChatsHome({ chats, selected, setSelected }: { chats: any[]; selected: any; setSelected: (v: any) => void }) {
  const [search, setSearch] = useState(''); const [result, setResult] = useState<NaxUser | null>(null); const [busy, setBusy] = useState(false);
  const find = async () => { setBusy(true); try { setResult(await searchNaxUser(search)); } finally { setBusy(false); } };
  return <div className="grid gap-5 lg:grid-cols-[360px_1fr]"><section className="glass rounded-[28px] p-4"><div className="flex items-center justify-between px-2 pb-4"><div><h1 className="text-2xl font-black">Chats</h1><p className="text-xs text-slate-500">Private conversations</p></div><span className="rounded-full bg-cyan-400/10 px-3 py-1 text-[10px] text-cyan-300">NAX CHAT</span></div><div className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-600" /><input value={search} onChange={(e) => setSearch(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && find()} placeholder="@username" className="w-full rounded-xl border border-white/10 bg-black/20 py-3 pl-9 pr-3 text-sm outline-none focus:border-cyan-400/40" /></div><button onClick={find} className="rounded-xl bg-white/10 px-4 text-sm">{busy ? '…' : 'Find'}</button></div>{result && <button onClick={async () => { const id = await createPrivateChat(result); setSelected({ chatId: id, friendName: result.name, friendId: result.uid }); setResult(null); setSearch(''); }} className="mt-3 flex w-full items-center gap-3 rounded-xl bg-cyan-400/10 p-3 text-left"><UserRound className="h-5 w-5 text-cyan-300" /><span><b className="block text-sm">{result.name}</b><small className="text-slate-500">{result.username}{result.isBot ? ' · Bot' : ''}</small></span><Plus className="ml-auto h-4 w-4" /></button>}<div className="mt-4 space-y-2">{chats.map((chat) => <button key={chat.id} onClick={() => setSelected(chat)} className={`w-full rounded-2xl p-3 text-left transition ${selected?.id === chat.id ? 'bg-white/10' : 'hover:bg-white/5'}`}><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-500/10"><MessageCircle className="h-5 w-5 text-indigo-300" /></div><div className="min-w-0"><b className="block truncate text-sm">{chat.friendName || 'Nax User'}</b><span className="text-xs text-slate-500">{chat.friendUsername || 'Private chat'}</span></div></div></button>)}{chats.length === 0 && <p className="py-10 text-center text-xs text-slate-600">Search @username to start a chat.</p>}</div><button onClick={() => setSelected({ chatId: 'global_chats', friendName: 'Global Room' })} className="mt-3 flex w-full items-center gap-3 rounded-2xl border border-white/10 p-3 text-left hover:bg-white/5"><Globe2 className="h-5 w-5 text-cyan-300" /><span><b className="block text-sm">Global Room</b><small className="text-slate-500">Public chat</small></span></button></section>{selected ? <ChatRoom chat={selected} /> : <FeaturePlaceholder title="Select a conversation" icon={<MessageCircle />} text="Search a Nax user or choose a chat to begin." />}</div>;
}

function ChatRoom({ chat }: { chat: any }) { const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(''); useEffect(() => subscribeToMessages(chat.chatId || chat.id, setMessages), [chat.chatId, chat.id]); const send = async () => { if (!text.trim()) return; const value = text; setText(''); await sendTextMessage(chat.chatId || chat.id, value); }; return <section className="glass flex min-h-[70vh] flex-col rounded-[28px] p-5"><div className="border-b border-white/10 pb-4"><h2 className="font-bold">{chat.friendName || 'Global Room'}</h2><p className="text-xs text-slate-500">{chat.friendUsername || 'Nax Chat'}</p></div><div className="flex-1 space-y-3 overflow-auto py-5">{messages.map((m) => <div key={m.id} className={`max-w-[80%] rounded-2xl p-3 ${m.senderId === auth.currentUser?.uid ? 'ml-auto bg-indigo-500/20' : 'bg-white/5'}`}><p className="text-sm whitespace-pre-wrap">{m.text}</p><span className="mt-1 block text-[10px] text-slate-600">{m.senderName}</span></div>)}{messages.length === 0 && <p className="py-20 text-center text-sm text-slate-600">No messages yet. Say hello 👋</p>}</div><div className="flex gap-2"><input value={text} onChange={(e) => setText(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && send()} placeholder="Write a message…" className="flex-1 rounded-2xl border border-white/10 bg-black/20 px-4 py-3 outline-none focus:border-cyan-400/40" /><button onClick={send} className="rounded-2xl bg-gradient-to-r from-indigo-500 to-cyan-500 px-5"><Send className="h-5 w-5" /></button></div></section>; }

function DropHome() { const { init, sendFile, acceptDownload, cancelTransfer, status, progress, roomCode, incomingFile, stats } = useWebRTC(process.env.NEXT_PUBLIC_SIGNALING_URL || 'ws://localhost:8080'); const [code, setCode] = useState(''); const active = status !== 'disconnected'; return <section className="mx-auto max-w-4xl"><div className="mb-6 text-center"><span className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-slate-400"><Wifi className="h-3 w-3 text-cyan-300" /> P2P transfer</span><h1 className="text-4xl font-black">Drop files <span className="text-cyan-300">directly.</span></h1><p className="mt-2 text-sm text-slate-500">Nax Chat features + HyperDrop's device-to-device transfer.</p></div>{!active ? <div className="grid gap-4 md:grid-cols-2"><div className="glass rounded-[28px] p-6"><h2 className="font-bold">Send</h2><p className="mt-1 text-sm text-slate-500">Create a private room.</p><button onClick={() => init()} className="mt-6 w-full rounded-2xl bg-gradient-to-r from-indigo-500 to-cyan-500 py-3 font-bold">Create room</button></div><div className="glass rounded-[28px] p-6"><h2 className="font-bold">Receive</h2><p className="mt-1 text-sm text-slate-500">Enter a 6-digit code.</p><input value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, '').slice(0, 6))} className="mt-5 w-full rounded-2xl border border-white/10 bg-black/20 p-3 text-center font-mono text-2xl tracking-widest" placeholder="000000" /><button disabled={code.length !== 6} onClick={() => init(code)} className="mt-3 w-full rounded-2xl bg-white/10 py-3 font-bold disabled:opacity-30">Connect</button></div></div> : <div className="glass rounded-[28px] p-6 text-center">{status === 'waiting_for_receiver' ? <><p className="text-xs uppercase tracking-widest text-slate-500">Share code</p><div className="my-4 font-mono text-5xl tracking-widest">{roomCode}</div><p className="text-sm text-slate-500">Waiting for receiver…</p></> : status === 'incoming_file' && incomingFile ? <><p className="text-xs text-slate-500">Incoming file</p><h2 className="mt-2 text-2xl font-bold">{incomingFile.name}</h2><p className="mt-1 text-sm text-slate-500">{formatBytes(incomingFile.size)}</p><button onClick={acceptDownload} className="mt-6 rounded-2xl bg-gradient-to-r from-cyan-500 to-indigo-500 px-7 py-3 font-bold">Accept & save</button></> : <><TransferZone status={status} progress={progress} onSendFile={sendFile} onCancel={cancelTransfer} /><div className="mt-4 flex justify-center gap-2 text-xs text-slate-500"><span className="rounded-full bg-white/5 px-3 py-1.5">{formatBytes(stats.speed)}/s</span><span className="rounded-full bg-white/5 px-3 py-1.5">{formatBytes(stats.transferred)} / {formatBytes(stats.total)}</span></div></>}<button onClick={cancelTransfer} className="mt-5 text-xs text-slate-600 hover:text-red-300"><X className="mr-1 inline h-3 w-3" /> End transfer</button></div>}</section>; }

function FeaturePlaceholder({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <div className="glass flex min-h-[55vh] flex-col items-center justify-center rounded-[32px] p-8 text-center"><div className="mb-5 flex h-20 w-20 items-center justify-center rounded-3xl bg-white/5 text-cyan-300">{React.cloneElement(icon as React.ReactElement, { className: 'h-9 w-9' })}</div><h2 className="text-3xl font-black">{title}</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">{text}</p></div>; }
