import React,{useEffect,useState}from'react';
import{View,Text,StyleSheet,Image,TouchableOpacity,Modal,SafeAreaView,Linking,TextInput,Alert}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{useTheme}from'../../context/ThemeContext';
import{auth}from'../../firebaseConfig';
import{Video,ResizeMode,Audio}from'expo-av';
import*as FileSystem from'expo-file-system';
import{deleteCloudinaryByToken}from'../../utils/cloudinaryUpload';
import MessagingService from'../../messaging/MessagingService';

function VoiceNote({uri,isDark}){const[sound,setSound]=useState(null);const[playing,setPlaying]=useState(false);useEffect(()=>()=>{sound?.unloadAsync().catch(()=>{})},[sound]);const toggle=async()=>{try{if(sound){if(playing){await sound.pauseAsync();setPlaying(false)}else{await sound.playAsync();setPlaying(true)}return}const r=await Audio.Sound.createAsync({uri});setSound(r.sound);r.sound.setOnPlaybackStatusUpdate(st=>{if(st.didJustFinish){setPlaying(false);r.sound.setPositionAsync(0).catch(()=>{})}});await r.sound.playAsync();setPlaying(true)}catch(e){}};return <TouchableOpacity style={[s.voiceBtn,{backgroundColor:isDark?'#21384A':'#EEF5FF'}]}onPress={toggle}><Ionicons name={playing?'pause':'play'}size={20}color="#087EFF"/><View style={s.wave}><View style={s.waveLine}/><View style={s.waveLine}/><View style={s.waveLine}/><View style={s.waveLine}/><View style={s.waveLine}/></View><Text style={{fontSize:11,color:'#087EFF',fontWeight:'700'}}>Voice</Text></TouchableOpacity>}

export default function MessageBubble({item,isMe,isGlobal,chatId,onReply}){
 const{isDark}=useTheme();const[imageOpen,setImageOpen]=useState(false);const[actionOpen,setActionOpen]=useState(false);const[editOpen,setEditOpen]=useState(false);const[editText,setEditText]=useState(item.text||'');const[local,setLocal]=useState(item.fileUri);
 const other=isDark?'#F4F7FA':'#142532',sub=isDark?'#8FA6B9':'#6C8494';
 const time=t=>{if(!t)return'';const d=t.toDate?t.toDate():new Date(t);return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};
 useEffect(()=>{let mounted=true;(async()=>{if(!isMe&&item.fileUri&&item.deleteToken){try{const ext=item.fileName?.includes('.')?item.fileName.slice(item.fileName.lastIndexOf('.')):(item.type==='video'?'.mp4':item.type==='image'?'.jpg':'.bin');const path=`${FileSystem.documentDirectory}nax_media_${item.id}${ext}`;const info=await FileSystem.getInfoAsync(path);const r=info.exists?{uri:path,status:200}:await FileSystem.downloadAsync(item.fileUri,path);if(r.status===200&&mounted){setLocal(r.uri);await deleteCloudinaryByToken(item.deleteToken)}}catch(e){}}})();return()=>{mounted=false}},[item.fileUri,item.deleteToken,item.id,isMe]);
 const reactionValues=Object.values(item.reactions||{});const readBy=Object.keys(item.readBy||{}).some(k=>!isMe||k);const delivered=Object.keys(item.deliveredTo||{}).length>0;
 const choose=async action=>{setActionOpen(false);try{if(action==='reply')onReply?.(item);if(action==='react')await MessagingService.toggleReaction(chatId,item.id,'❤️');if(action==='star')await MessagingService.toggleStar(chatId,item.id);if(action==='pin')await MessagingService.pinMessage(chatId,item.id);if(action==='delete')await MessagingService.deleteMessage(chatId,item.id,true);if(action==='edit'){setEditText(item.text||'');setEditOpen(true)}if(action==='forward')onForward?.(item)}catch(e){Alert.alert('Message',e.message||'Action failed.')}};
 return <View style={[s.wrap,isMe?s.me:s.other]}>
  {!isMe&&isGlobal?<Text style={[s.sender,{color:sub}]}>@{item.senderName}</Text>:null}
  <TouchableOpacity activeOpacity={.9} onLongPress={()=>setActionOpen(true)} style={[s.bubble,isMe?s.bubbleMe:{backgroundColor:theme.bubbleOther,borderColor:theme.border,borderWidth:1}]}>
   {item.replyToText?<View style={[s.reply,{borderLeftColor:isMe?'#FFF':'#087EFF'}]}><Text style={{color:isMe?'rgba(255,255,255,.8)':sub,fontSize:11}}>{item.replyToSenderName||'Reply'}</Text><Text style={{color:isMe?'#FFF':other,fontSize:12}} numberOfLines={1}>{item.replyToText}</Text></View>:null}
   {item.deleted?<Text style={[s.deleted,{color:isMe?'rgba(255,255,255,.75)':sub}]}>This message was deleted</Text>:null}
   {item.type==='image'&&item.fileUri?(item.viewOnce&&!isMe&&!openedOnce?<TouchableOpacity style={[s.onceBox,{backgroundColor:theme.input,borderColor:theme.border}]} onPress={async()=>{await MessagingService.openViewOnce(chatId,item.id).catch(()=>{});setOpenedOnce(true);setImageOpen(true)}}><Ionicons name="eye-outline" size={28} color={theme.blue}/><Text style={{color:theme.text,fontWeight:'800',marginTop:6}}>Open once</Text></TouchableOpacity>:item.viewOnce&&!isMe&&openedOnce?<Text style={{color:sub,fontStyle:'italic'}}>Opened once</Text>:<TouchableOpacity onPress={()=>setImageOpen(true)}><Image source={{uri:local||item.fileUri}} style={s.image}/></TouchableOpacity>):null}
   {item.type==='video'&&item.fileUri?<Video style={s.video} source={{uri:local||item.fileUri}} useNativeControls resizeMode={ResizeMode.COVER}/>:null}
   {item.type==='file'&&item.fileUri?<TouchableOpacity onPress={()=>Linking.openURL(local||item.fileUri)} style={s.file}><Ionicons name="document-text"size={28}color={isMe?'#FFF':'#087EFF'}/><Text style={{color:isMe?'#FFF':other,flex:1,marginLeft:8}}numberOfLines={1}>{item.fileName||'File'}</Text></TouchableOpacity>:null}
   {item.type==='voice'&&item.fileUri?<VoiceNote uri={local||item.fileUri} isDark={isDark}/>:null}
   {item.type==='location'&&item.location?<TouchableOpacity style={s.special}><Ionicons name="location"size={28}color="#FF9500"/><Text style={{color:isMe?'#FFF':other}}>Shared location</Text></TouchableOpacity>:null}
   {item.type==='contact'&&item.contact?<View style={s.special}><Ionicons name="person-circle"size={30}color="#5856D6"/><View><Text style={{color:isMe?'#FFF':other,fontWeight:'700'}}>{item.contact.name||'Contact'}</Text><Text style={{color:isMe?'rgba(255,255,255,.7)':sub}}>{item.contact.phone||''}</Text></View></View>:null}
   {item.type==='poll'&&item.poll?<View><Text style={{color:isMe?'#FFF':other,fontWeight:'800'}}>{item.poll.question}</Text>{(item.poll.options||[]).map((o,i)=>{const votes=Object.values(item.poll.votes||{});const count=votes.filter(v=>v===i).length;const mine=auth.currentUser?.uid&&item.poll.votes?.[auth.currentUser.uid]===i;return <TouchableOpacity key={i} onPress={()=>MessagingService.votePoll(chatId,item.id,i).catch(e=>Alert.alert('Poll',e.message||'Vote failed'))} style={[s.pollOption,{borderColor:theme.border,backgroundColor:mine?'rgba(8,126,255,.12)':theme.input}]}><Text style={{color:other,flex:1}}>{o}</Text><Text style={{color:theme.sub,fontWeight:'800'}}>{count}</Text></TouchableOpacity>})}</View>:null}
   {item.text&&item.type!=='location'&&item.type!=='contact'&&item.type!=='poll'&&item.text!=='This message was deleted'?<Text style={[s.msg,{color:isMe?'#FFF':other}]}>{item.text}</Text>:null}
   <View style={s.meta}><Text style={{color:isMe?'rgba(255,255,255,.7)':sub,fontSize:10}}>{time(item.createdAt)}{item.editedAt?' · edited':''}</Text>{isMe?<Ionicons name={readBy?'checkmark-done':delivered?'checkmark-done':'checkmark'}size={14}color={readBy?'#9FE8FF':isMe?'rgba(255,255,255,.7)':sub}/>:null}</View>
  </TouchableOpacity>
  {reactionValues.length>0?<View style={[s.reactions,{backgroundColor:isDark?'#14202E':'#FFF'}]}><Text>{reactionValues.slice(0,4).join(' ')}</Text><Text style={{fontSize:10,color:sub}}> {reactionValues.length}</Text></View>:null}
  <Modal visible={imageOpen}transparent animationType="fade"onRequestClose={()=>setImageOpen(false)}><SafeAreaView style={s.full}><TouchableOpacity onPress={()=>setImageOpen(false)}style={s.close}><Ionicons name="close"size={30}color="#FFF"/></TouchableOpacity><Image source={{uri:local||item.fileUri}}style={s.fullImg}resizeMode="contain"/></SafeAreaView></Modal>
  <Modal visible={actionOpen}transparent animationType="slide"onRequestClose={()=>setActionOpen(false)}><TouchableOpacity style={s.sheetBg}activeOpacity={1}onPress={()=>setActionOpen(false)}><View style={[s.sheet,{backgroundColor:isDark?'#132B3B':'#FFF'}]}>{[['reply','Reply','return-up-forward'],['forward','Forward','arrow-redo-outline'],['react','React ❤️','heart'],['star','Star','star'],['pin','Pin','pin'],...(isMe?[['edit','Edit','create-outline'],['delete','Delete','trash']]:[])].map(([a,t,i])=><TouchableOpacity key={a}style={s.action}onPress={()=>choose(a)}><Ionicons name={i}size={21}color={a==='delete'?'#FF3B30':isDark?'#FFF':'#142532'}/><Text style={{fontSize:15,fontWeight:'700',color:a==='delete'?'#FF3B30':isDark?'#FFF':'#142532'}}>{t}</Text></TouchableOpacity>)}</View></TouchableOpacity></Modal>
  <Modal visible={editOpen}transparent animationType="fade"onRequestClose={()=>setEditOpen(false)}><View style={s.editBg}><View style={[s.editCard,{backgroundColor:isDark?'#132B3B':'#FFF'}]}><Text style={{fontSize:16,fontWeight:'800',color:isDark?'#FFF':'#142532'}}>Edit message</Text><TextInput value={editText}onChangeText={setEditText}style={[s.editInput,{color:isDark?'#FFF':'#142532'}]}autoFocus/><View style={s.editRow}><TouchableOpacity onPress={()=>setEditOpen(false)}><Text>Cancel</Text></TouchableOpacity><TouchableOpacity onPress={async()=>{try{await MessagingService.editMessage(chatId,item.id,editText);setEditOpen(false)}catch(e){Alert.alert('Edit',e.message)}}}><Text style={{color:'#087EFF',fontWeight:'800'}}>Save</Text></TouchableOpacity></View></View></View></Modal>
 </View>
}
const s=StyleSheet.create({wrap:{marginBottom:10,maxWidth:'84%'},me:{alignSelf:'flex-end'},other:{alignSelf:'flex-start'},sender:{fontSize:11,marginBottom:4,marginLeft:4,fontWeight:'700'},bubble:{padding:10,borderRadius:18},bubbleMe:{backgroundColor:'#087EFF',borderBottomRightRadius:4},msg:{fontSize:15,lineHeight:21},deleted:{fontStyle:'italic'},reply:{borderLeftWidth:3,paddingLeft:8,marginBottom:6},image:{width:220,height:220,borderRadius:16},onceBox:{width:220,height:150,borderRadius:16,borderWidth:1,alignItems:'center',justifyContent:'center'},pollOption:{flexDirection:'row',alignItems:'center',borderWidth:1,borderRadius:13,padding:11,marginTop:7},video:{width:220,height:200,borderRadius:12,backgroundColor:'#000'},voice:{width:210,height:48},voiceBtn:{width:210,height:52,borderRadius:14,flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:9},wave:{flex:1,height:24,flexDirection:'row',alignItems:'center',justifyContent:'space-around'},waveLine:{width:3,height:12,borderRadius:2,backgroundColor:'#087EFF'},file:{flexDirection:'row',alignItems:'center',width:220},special:{flexDirection:'row',alignItems:'center',gap:9},meta:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:3,marginTop:4},reactions:{position:'relative',alignSelf:'flex-end',marginTop:-4,borderRadius:12,paddingHorizontal:8,paddingVertical:3,elevation:2},full:{flex:1,backgroundColor:'rgba(0,0,0,.95)',justifyContent:'center'},fullImg:{width:'100%',height:'80%'},close:{position:'absolute',top:50,right:20,zIndex:2},sheetBg:{flex:1,backgroundColor:'rgba(0,0,0,.45)',justifyContent:'flex-end'},sheet:{padding:14,borderTopLeftRadius:22,borderTopRightRadius:22},action:{paddingVertical:15,flexDirection:'row',alignItems:'center',gap:12},editBg:{flex:1,backgroundColor:'rgba(0,0,0,.5)',justifyContent:'center',padding:20},editCard:{borderRadius:18,padding:18},editInput:{borderWidth:1,borderColor:'#D9DEE7',borderRadius:12,padding:12,marginTop:12,minHeight:80},editRow:{flexDirection:'row',justifyContent:'flex-end',gap:22,marginTop:14}});
