import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../context/ThemeContext';
import { auth } from '../firebaseConfig';
import CreatorAnalyticsAPI from '../api/CreatorAnalyticsAPI';

export default function CreatorAnalyticsScreen({ navigation }) {
  const { theme } = useTheme();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const load = useCallback(async (pull=false) => {
    pull ? setRefreshing(true) : setLoading(true);
    try { setData(await CreatorAnalyticsAPI.getCreatorAnalytics(auth.currentUser?.uid)); }
    catch (_) {}
    finally { pull ? setRefreshing(false) : setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  const topAssets = useMemo(() => [...(data?.apps || []), ...(data?.bots || [])]
    .sort((a,b) => (Number(b.opens||0)+Number(b.actions||0)) - (Number(a.opens||0)+Number(a.actions||0)))
    .slice(0, 8), [data]);

  const total = data?.totals || {};
  const Card = ({ icon, label, value }) => (
    <View style={[styles.metric,{backgroundColor:theme.surface,borderColor:theme.border}]}>
      <View style={[styles.metricIcon,{backgroundColor:'rgba(8,126,255,.10)'}]}><Ionicons name={icon} size={18} color={theme.blue}/></View>
      <Text style={[styles.metricValue,{color:theme.text}]}>{Number(value||0).toLocaleString()}</Text>
      <Text style={[styles.metricLabel,{color:theme.sub}]}>{label}</Text>
    </View>
  );

  return <SafeAreaView style={[styles.safe,{backgroundColor:theme.bg}]}>
    <View style={[styles.header,{borderBottomColor:theme.border}]}>
      <TouchableOpacity onPress={()=>navigation.goBack()} style={styles.back}><Ionicons name="chevron-back" size={27} color={theme.text}/></TouchableOpacity>
      <View style={{flex:1}}><Text style={[styles.title,{color:theme.text}]}>Creator Analytics</Text><Text style={[styles.sub,{color:theme.sub}]}>Your apps, bots and usage</Text></View>
      <TouchableOpacity onPress={()=>load(true)} style={styles.back}><Ionicons name="refresh-outline" size={21} color={theme.text}/></TouchableOpacity>
    </View>
    {loading ? <View style={styles.center}><ActivityIndicator size="large" color={theme.blue}/></View> :
    <ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>load(true)}/>} contentContainerStyle={styles.content}>
      <View style={styles.hero}><Text style={styles.heroEyebrow}>CREATOR OVERVIEW</Text><Text style={styles.heroTitle}>{total.assets || 0} published assets</Text><Text style={styles.heroText}>Track usage generated by your Nax apps and bots. Analytics are tied to your creator account.</Text></View>
      <View style={styles.grid}>
        <Card icon="people-outline" label="Unique Users" value={total.uniqueUsers}/>
        <Card icon="eye-outline" label="Opens" value={total.opens}/>
        <Card icon="flash-outline" label="Actions" value={total.actions}/>
        <Card icon="share-social-outline" label="Shares" value={total.shares}/>
      </View>
      <Text style={[styles.section,{color:theme.text}]}>Your Apps</Text>
      {(data?.apps || []).length === 0 ? <Text style={[styles.empty,{color:theme.sub}]}>No app analytics yet. Publish and share an app to start collecting data.</Text> :
        (data.apps || []).map(item => <AssetRow key={'a'+item.id} item={item} theme={theme} icon="apps-outline"/>)}
      <Text style={[styles.section,{color:theme.text}]}>Your Bots</Text>
      {(data?.bots || []).length === 0 ? <Text style={[styles.empty,{color:theme.sub}]}>No bot analytics yet. Use or share a converted/public bot.</Text> :
        (data.bots || []).map(item => <AssetRow key={'b'+item.id} item={item} theme={theme} icon="logo-ionitron"/>)}
      <Text style={[styles.section,{color:theme.text}]}>Most Active</Text>
      {topAssets.map(item => <AssetRow key={'t'+item.sourceType+item.id} item={item} theme={theme} icon={item.sourceType==='bot'?'logo-ionitron':'apps-outline'}/>)}
    </ScrollView>}
  </SafeAreaView>;
}

function AssetRow({item,theme,icon}) {
  return <View style={[styles.row,{backgroundColor:theme.surface,borderColor:theme.border}]}>
    <View style={styles.rowIcon}><Ionicons name={icon} size={19} color={theme.blue}/></View>
    <View style={{flex:1}}><Text style={[styles.rowTitle,{color:theme.text}]} numberOfLines={1}>{item.name || item.title || (item.sourceType==='bot'?'Bot':'Nax App')}</Text><Text style={[styles.rowSub,{color:theme.sub}]}>{item.sourceType==='bot'?'Bot':'App'} · {Number(item.uniqueUsers||0)} users · {Number(item.opens||0)} opens</Text></View>
    <View style={styles.stats}><Text style={[styles.stat,{color:theme.text}]}>{Number(item.actions||0)}</Text><Text style={[styles.statLabel,{color:theme.sub}]}>actions</Text></View>
  </View>;
}
const styles=StyleSheet.create({
 safe:{flex:1},header:{height:62,borderBottomWidth:1,flexDirection:'row',alignItems:'center',paddingHorizontal:9},back:{width:42,height:42,alignItems:'center',justifyContent:'center'},title:{fontSize:18,fontWeight:'900'},sub:{fontSize:10,marginTop:2},content:{padding:14,paddingBottom:60},center:{flex:1,alignItems:'center',justifyContent:'center'},hero:{padding:18,borderRadius:20,backgroundColor:'#087EFF',marginBottom:12},heroEyebrow:{fontSize:9,fontWeight:'900',color:'#D9ECFF'},heroTitle:{fontSize:25,fontWeight:'900',color:'#FFF',marginTop:5},heroText:{fontSize:11,lineHeight:16,color:'#EAF5FF',marginTop:5},grid:{flexDirection:'row',flexWrap:'wrap',gap:9},metric:{width:'48%',minHeight:105,borderRadius:17,borderWidth:1,padding:12},metricIcon:{width:34,height:34,borderRadius:11,alignItems:'center',justifyContent:'center'},metricValue:{fontSize:20,fontWeight:'900',marginTop:7},metricLabel:{fontSize:10,fontWeight:'700',marginTop:1},section:{fontSize:16,fontWeight:'900',marginTop:23,marginBottom:9},empty:{fontSize:11,lineHeight:17},row:{minHeight:67,borderWidth:1,borderRadius:15,padding:10,flexDirection:'row',alignItems:'center',marginBottom:7},rowIcon:{width:38,height:38,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(8,126,255,.08)'},rowTitle:{fontSize:12,fontWeight:'900'},rowSub:{fontSize:9,marginTop:3},stats:{alignItems:'flex-end',marginLeft:8},stat:{fontSize:14,fontWeight:'900'},statLabel:{fontSize:8}
});
