import React,{useState}from'react';
import{SafeAreaView,ScrollView,View,Text,TextInput,TouchableOpacity,StyleSheet,Alert}from'react-native';
import{collection,query,where,getDocs}from'firebase/firestore';
import{db}from'../firebaseConfig';
import MessagingService from'../messaging/MessagingService';

export default function MessagingHubScreen({navigation}){
 const[group,setGroup]=useState('');const[members,setMembers]=useState('');const[channel,setChannel]=useState('');const[description,setDescription]=useState('');const[community,setCommunity]=useState('');const[status,setStatus]=useState('');
 const resolveMembers=async()=>{const names=members.split(',').map(v=>v.trim().replace(/^@/,'').toLowerCase()).filter(Boolean);if(!names.length)return[];const found=[];for(const name of names){const snap=await getDocs(query(collection(db,'users'),where('usernameLower','==',name)));if(!snap.empty)found.push(snap.docs[0].id);}return found};
 const createGroup=async()=>{try{if(!group.trim())throw new Error('Group name required.');const ids=await resolveMembers();const id=await MessagingService.createGroup(group,ids);Alert.alert('Group created','Group is ready.',[{text:'Open',onPress:()=>navigation.navigate('ChatRoom',{chatId:id,chatName:group,type:'group'})}]);}catch(e){Alert.alert('Group',e.message)}};
 const createChannel=async()=>{try{const r=await MessagingService.createChannel(channel,description);Alert.alert('Channel created','Channel ID: '+r.id)}catch(e){Alert.alert('Channel',e.message)}};
 const createCommunity=async()=>{try{const r=await MessagingService.createCommunity(community);Alert.alert('Community created','Community ID: '+r.id)}catch(e){Alert.alert('Community',e.message)}};
 const postStatus=async()=>{try{await MessagingService.createStatus({type:'text',text:status});setStatus('');Alert.alert('Status posted','यह status 24 hours के लिए रहेगा.')}catch(e){Alert.alert('Status',e.message)}};
 return <SafeAreaView style={s.safe}><View style={s.header}><TouchableOpacity onPress={()=>navigation.goBack()}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.title}>Messaging Hub</Text><View style={{width:30}}/></View><ScrollView contentContainerStyle={s.content}>
  <Text style={s.heading}>Groups</Text><View style={s.card}><TextInput value={group}onChangeText={setGroup}placeholder="Group name"style={s.input}/><TextInput value={members}onChangeText={setMembers}placeholder="@username, @username"style={s.input}/><Text style={s.note}>Members username से add होंगे.</Text><TouchableOpacity style={s.primary}onPress={createGroup}><Text style={s.primaryText}>Create Group</Text></TouchableOpacity></View>
  <Text style={s.heading}>Channels</Text><View style={s.card}><TextInput value={channel}onChangeText={setChannel}placeholder="Channel name"style={s.input}/><TextInput value={description}onChangeText={setDescription}placeholder="Description"style={s.input}/><TouchableOpacity style={s.primary}onPress={createChannel}><Text style={s.primaryText}>Create Channel</Text></TouchableOpacity></View>
  <Text style={s.heading}>Communities</Text><View style={s.card}><TextInput value={community}onChangeText={setCommunity}placeholder="Community name"style={s.input}/><TouchableOpacity style={s.primary}onPress={createCommunity}><Text style={s.primaryText}>Create Community</Text></TouchableOpacity></View>
  <Text style={s.heading}>Status / Story</Text><View style={s.card}><TextInput value={status}onChangeText={setStatus}placeholder="What's happening?"multiline style={[s.input,{minHeight:90,textAlignVertical:'top'}]}/><TouchableOpacity style={s.primary}onPress={postStatus}><Text style={s.primaryText}>Post for 24h</Text></TouchableOpacity></View>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#F5F7FA'},header:{height:58,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,backgroundColor:'#FFF',borderBottomWidth:1,borderBottomColor:'#E4E7EB'},back:{fontSize:34},title:{fontSize:18,fontWeight:'800'},content:{padding:16,paddingBottom:50},heading:{fontSize:18,fontWeight:'800',marginTop:8,marginBottom:10},card:{backgroundColor:'#FFF',borderRadius:16,padding:14,marginBottom:14,borderWidth:1,borderColor:'#E5E7EB'},input:{height:48,borderWidth:1,borderColor:'#DDE2E8',borderRadius:12,paddingHorizontal:12,marginBottom:9,backgroundColor:'#FAFBFC'},note:{fontSize:11,color:'#7A8494',marginBottom:9},primary:{height:44,borderRadius:12,backgroundColor:'#087EFF',alignItems:'center',justifyContent:'center'},primaryText:{color:'#FFF',fontWeight:'800'}});
