import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, SafeAreaView, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../context/ThemeContext';
import OnDeviceModelCatalog from '../ai/on-device/OnDeviceModelCatalog';
import DeviceCapabilityService from '../ai/on-device/DeviceCapabilityService';
import ModelCompatibilityService from '../ai/on-device/ModelCompatibilityService';
import ModelDownloadService from '../ai/on-device/ModelDownloadService';
import OnDeviceAIService from '../ai/on-device/OnDeviceAIService';

const MB = 1024 * 1024;
export default function OnDeviceAISettingsScreen({ navigation }) {
  const { isDark } = useTheme();
  const [device, setDevice] = useState(null);
  const [models, setModels] = useState([]);
  const [installed, setInstalled] = useState([]);
  const [busy, setBusy] = useState({});
  const [loading, setLoading] = useState(true);
  const bg = isDark ? '#050A10' : '#F3F7FA'; const card = isDark ? '#101A26' : '#FFF'; const text = isDark ? '#F4F7FA' : '#142532'; const sub = isDark ? '#8FA6B9' : '#6C8494'; const border = isDark ? 'rgba(255,255,255,.08)' : 'rgba(0,0,0,.06)'; const purple = '#AF52DE'; const green = '#34C759'; const blue = '#087EFF';
  const load = async () => { setLoading(true); try { const caps = await DeviceCapabilityService.scan(); const catalog = await OnDeviceModelCatalog.loadCached(); setDevice(caps); setModels(ModelCompatibilityService.rank(catalog, caps)); setInstalled(await ModelDownloadService.listInstalled()); } catch (e) { Alert.alert('Offline AI', e?.message || 'Could not inspect this device.'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const installedFor = model => installed.some(item => item.name === `${String(model.id).replace(/[^a-zA-Z0-9._-]/g, '_')}.gguf`);
  const action = async model => { setBusy(v => ({ ...v, [model.id]: true })); try { if (installedFor(model)) { await OnDeviceAIService.test(model); Alert.alert('Offline AI', 'Model loaded and replied successfully.'); } else { await OnDeviceAIService.downloadModel(model, progress => setBusy(v => ({ ...v, [model.id]: `${Math.round(progress * 100)}%` }))); Alert.alert('Downloaded', 'Model is now stored on this phone and can run without internet.'); } await load(); } catch (e) { Alert.alert('Offline AI', e?.message || 'Operation failed.'); } finally { setBusy(v => ({ ...v, [model.id]: false })); } };
  if (loading) return <SafeAreaView style={[styles.container,{backgroundColor:bg}]}><View style={styles.center}><ActivityIndicator size="large" color={purple}/></View></SafeAreaView>;
  return <SafeAreaView style={[styles.container,{backgroundColor:bg}]}><View style={[styles.header,{backgroundColor:card,borderBottomColor:border}]}><TouchableOpacity onPress={()=>navigation.goBack()}><Ionicons name="chevron-back" size={28} color={text}/></TouchableOpacity><View style={{flex:1,alignItems:'center'}}><Text style={[styles.title,{color:text}]}>📱 Offline AI</Text><Text style={[styles.subtitle,{color:sub}]}>Downloaded model • no internet needed</Text></View><TouchableOpacity onPress={load}><Ionicons name="refresh" size={22} color={blue}/></TouchableOpacity></View><ScrollView contentContainerStyle={styles.scroll}>
    <View style={[styles.card,{backgroundColor:card,borderColor:border}]}><Text style={[styles.cardTitle,{color:text}]}>Device capability</Text><Text style={[styles.meta,{color:sub}]}>{device.model} • {device.platform} {device.osVersion}</Text><View style={styles.stats}><Text style={[styles.stat,{color:text}]}>RAM: {device.ramGB ? `${device.ramGB} GB` : 'Unknown'}</Text><Text style={[styles.stat,{color:text}]}>Free: {device.freeStorageGB ? `${device.freeStorageGB} GB` : 'Unknown'}</Text><Text style={[styles.stat,{color:text}]}>CPU: {device.architectures?.join(', ') || 'Unknown'}</Text><Text style={[styles.stat,{color:text}]}>Backend: {device.gpuBackend}</Text></View><Text style={[styles.helper,{color:sub}]}>Nax keeps a conservative memory budget so the model does not consume all phone RAM.</Text></View>
    <Text style={[styles.section,{color:sub}]}>MODEL CATALOG</Text>{models.map(model => { const c=model.compatibility; const isInstalled=installedFor(model); const label=busy[model.id] || (isInstalled ? 'Test offline' : c.status==='unsupported' ? c.label : 'Download'); const tint=c.status==='supported'?green:c.status==='heavy'?'#FF9500':'#FF3B30'; return <View key={model.id} style={[styles.card,{backgroundColor:card,borderColor:c.status==='supported'?green:border}]}><View style={{flexDirection:'row',alignItems:'center'}}><View style={{flex:1}}><Text style={[styles.name,{color:text}]}>{model.name}</Text><Text style={[styles.meta,{color:sub}]}>{model.parametersB}B • {model.quantization} • ~{model.sizeMB} MB • ~{model.estimatedRamMB} MB RAM</Text></View><View style={[styles.badge,{backgroundColor:tint+'20'}]}><Text style={{color:tint,fontSize:10,fontWeight:'900'}}>{c.label}</Text></View></View><Text style={[styles.reason,{color:sub}]}>{c.reason}</Text><TouchableOpacity disabled={c.status==='unsupported' || !!busy[model.id]} onPress={()=>action(model)} style={[styles.btn,{backgroundColor:c.status==='unsupported'?'#777':purple}]}><Text style={styles.btnText}>{label}</Text></TouchableOpacity>{isInstalled?<TouchableOpacity onPress={async()=>{await OnDeviceAIService.removeModel(model);await load();}}><Text style={[styles.remove,{color:'#FF3B30'}]}>Delete downloaded model</Text></TouchableOpacity>:null}</View>})}
    <View style={[styles.card,{backgroundColor:card,borderColor:border}]}><Text style={[styles.cardTitle,{color:text}]}>Dynamic catalog</Text><Text style={[styles.helper,{color:sub}]}>The app keeps a small verified seed catalog offline and can discover more Hugging Face GGUF repositories when you are online. Only models with a known GGUF file can be downloaded.</Text><TouchableOpacity style={[styles.btn,{backgroundColor:blue}]} onPress={async()=>{try{setLoading(true);const updated=await OnDeviceModelCatalog.refresh('Instruct GGUF');setModels(ModelCompatibilityService.rank(updated,device));}catch(e){Alert.alert('Catalog',e?.message||'Refresh failed.');}finally{setLoading(false);}}}><Text style={styles.btnText}>Discover more models</Text></TouchableOpacity></View>
  </ScrollView></SafeAreaView>;
}
const styles=StyleSheet.create({container:{flex:1},center:{flex:1,justifyContent:'center',alignItems:'center'},header:{flexDirection:'row',alignItems:'center',paddingHorizontal:14,paddingVertical:12,borderBottomWidth:1},title:{fontSize:18,fontWeight:'800'},subtitle:{fontSize:11,marginTop:2},scroll:{padding:18,paddingBottom:50},card:{borderRadius:18,borderWidth:1,padding:15,marginBottom:12},cardTitle:{fontSize:16,fontWeight:'800',marginBottom:5},meta:{fontSize:11,marginTop:3},stats:{marginTop:12,gap:5},stat:{fontSize:12,fontWeight:'700'},helper:{fontSize:12,lineHeight:18,marginTop:10},section:{fontSize:11,fontWeight:'900',letterSpacing:1,marginVertical:12},name:{fontSize:15,fontWeight:'800'},badge:{paddingHorizontal:8,paddingVertical:5,borderRadius:10},reason:{fontSize:11,lineHeight:16,marginTop:10},btn:{height:44,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:12},btnText:{color:'#FFF',fontWeight:'800'},remove:{fontSize:11,fontWeight:'800',textAlign:'center',paddingTop:12}}
);
